### ISSUE TITLE
calling url() on a popplerqt5.LinkBrowse returns a broken PyQt5.QtCore.QStorageInfo

### ISSUE THREAD

**Issue by syntaxaire** [frescobaldi/python-poppler-qt5#16] opened 2017-04-23 18:03 UTC
From wbsoft/frescobaldi#929:
Using Ubuntu 17.04 with python3-poppler-qt5 0.24.2-3 installed from apt-get, from Frescobaldi debug session:
```
In[6]: link
Out[7]: 
<popplerqt5.LinkBrowse at 0x7fe06ef0dee8>
In[7]: link.url()
Out[8]: 
<PyQt5.QtCore.QStorageInfo at 0x7fe06ed76eb8>
In[8]: url=link.url()
In[9]: url.name()
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

**Comment by wbsoft** [comment] 2019-09-18 15:26
thanks for reporting. Looks like a mismatch between libraries... can't reproduce.

**Comment by wbsoft** [comment] 2019-11-22 05:49
Closing, not a frescobaldi/popplerqt5 bug.

**Closed by wbsoft** 2019-11-22 05:49 UTC
